2021-11-05 14:43:24.475 | WARNING  | autodidaqt_common.remote.schema:get_definition:208 - Improperly handled type ObjectType()
2021-11-05 14:43:24.485 | WARNING  | autodidaqt_common.remote.schema:from_type:261 - Assuming naive implementation of Array and Object types.
2021-11-05 14:43:24.487 | INFO     | autodidaqt.core:start:768 - Application in startup.
2021-11-05 14:43:24.489 | INFO     | autodidaqt.core:start:769 - CommandLineConfig(headless=False, remote_config=None)
2021-11-05 14:43:24.491 | INFO     | autodidaqt.core:start:770 - {'version': '0.0.0', 'debug': True, 'logging': True, 'logging_directory': 'out\\logs', 'log_format': '{time}-{user}-{session}', 'save_format': 'pickle', 'data_directory': 'out\\data', 'data_format': '{user}\\{date}-{name}-{session}-{run}', 'maintain_state': True, 'state_directory': 'out\\state', 'instruments': {'simulate_instruments': False}, 'use_profiles': False, 'profiles': {}}
2021-11-05 14:43:25.461 | INFO     | autodidaqt.core:start:775 - Configuring Qt application and styles
2021-11-05 14:43:26.517 | INFO     | autodidaqt.core:configure_event_loop:746 - Configuring async runtime
2021-11-05 14:43:26.518 | INFO     | autodidaqt.core:configure_event_loop:753 - Using asyncio for async support.
2021-11-05 14:43:26.520 | INFO     | autodidaqt.core:configure_event_loop:763 - Setting custom exception handler on async loop
2021-11-05 14:43:35.135 | INFO     | autodidaqt.core:launch_panel:130 - Opening panel _instrument_manager
2021-11-05 14:43:35.206 | INFO     | autodidaqt.panels.instrument_manager:launch_panel:21 - Instrument Manager: Opening panel analyzer
2021-11-05 14:43:37.003 | INFO     | autodidaqt.panels.instrument_manager:launch_panel:21 - Instrument Manager: Opening panel phony
2021-11-05 14:43:37.304 | INFO     | autodidaqt.core:launch_panel:130 - Opening panel experiment
2021-11-05 14:43:37.367 | INFO     | autodidaqt.core:master:548 - Started async loop.
2021-11-05 14:43:37.369 | INFO     | autodidaqt.core:master:567 - Running actor .prepare
2021-11-05 14:43:37.371 | INFO     | autodidaqt.experiment.fsm:transition_to:42 - {'match': <ExperimentTransitions.Initialize: 'initialize'>, 'to': <ExperimentStates.Idle: 'IDLE'>}, initialize
2021-11-05 14:43:37.373 | INFO     | autodidaqt.core:master:584 - Installing Qt event processing on the standard event loop
2021-11-05 14:43:37.374 | INFO     | autodidaqt.core:load_state:690 - Loading application state.
2021-11-05 14:43:37.523 | INFO     | autodidaqt.core:load_state:694 - Found candidate application state: C:\Users\admin.TOF-PEEM\documents\peem-daq\out\state\2021-11-01T16-59-29-666325.state.pickle... loading.
2021-11-05 14:43:37.548 | INFO     | autodidaqt.core:load_state:719 - Finished loading application state.
2021-11-05 14:43:37.550 | INFO     | autodidaqt.core:master:589 - Main task is dropping into event loop
2021-11-05 14:43:37.552 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:43:46.579 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-05 14:43:46.589 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:43:55.633 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-05 14:43:55.641 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:44:04.694 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-05 14:44:04.706 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:44:13.728 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-05 14:44:13.738 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:44:22.764 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-05 14:44:22.774 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:44:31.795 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-05 14:44:31.804 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:44:40.876 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-05 14:44:40.883 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:44:49.909 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-05 14:44:49.914 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:44:59.009 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-05 14:44:59.021 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:45:08.098 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-05 14:45:08.104 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:45:17.174 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-05 14:45:17.190 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:45:26.282 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-05 14:45:26.288 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-05 14:45:30.094 | WARNING  | autodidaqt.core:shutdown:417 - Shutting down due to exception.
2021-11-05 14:45:30.097 | INFO     | autodidaqt.core:shutdown:419 - Shutting down process pool.
2021-11-05 14:45:30.100 | INFO     | autodidaqt.core:shutdown:421 - Finished shutting down process pool.
2021-11-05 14:45:30.102 | INFO     | autodidaqt.core:shutdown:423 - Saving...
2021-11-05 14:45:30.104 | INFO     | autodidaqt.core:save_state:722 - Saving application state.
2021-11-05 14:45:30.120 | INFO     | autodidaqt.core:save_state:730 - Finished saving application state.
2021-11-05 14:45:30.122 | INFO     | autodidaqt.core:shutdown:427 - Application is still reading messages. Stopping...
2021-11-05 14:45:30.124 | INFO     | autodidaqt.core:shutdown:431 - Sending graceful shutdown requests.
2021-11-05 14:45:30.126 | INFO     | autodidaqt.core:shutdown:441 - Waiting graceful shutdown requests.
2021-11-05 14:45:30.129 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:213 - Shutting down ['stages', 0]
2021-11-05 14:45:30.131 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:215 - Finished shutting down ['stages', 0]
2021-11-05 14:45:30.136 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:213 - Shutting down ['stages', 1]
2021-11-05 14:45:30.138 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:215 - Finished shutting down ['stages', 1]
2021-11-05 14:45:30.140 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:213 - Shutting down ['stages', 2]
2021-11-05 14:45:30.142 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:215 - Finished shutting down ['stages', 2]
2021-11-05 14:45:33.127 | ERROR    | autodidaqt.core:shutdown:449 - Not all actors have shut down after 3.0 seconds. Bad actors are ['analyzer']
2021-11-05 14:45:33.134 | INFO     | autodidaqt.core:shutdown:457 - Cancelling tasks...
2021-11-05 14:45:33.136 | INFO     | autodidaqt.core:shutdown:470 - Waiting on finished tasks...
2021-11-05 14:45:33.139 | INFO     | autodidaqt.core:shutdown:481 - Stopping loop
2021-11-05 14:45:33.141 | INFO     | autodidaqt.core:start:794 - Closed autodidaqt successfully.
