2022-06-28 13:40:07.859 | INFO     | autodidaqt.core:start:768 - Application in startup.
2022-06-28 13:40:07.859 | INFO     | autodidaqt.core:start:769 - CommandLineConfig(headless=False, remote_config=None)
2022-06-28 13:40:07.859 | INFO     | autodidaqt.core:start:770 - {'version': '0.0.0', 'debug': True, 'logging': True, 'logging_directory': 'out\\logs', 'log_format': '{time}-{user}-{session}', 'save_format': 'pickle', 'data_directory': 'out\\data', 'data_format': '{user}\\{date}-{session}-{run}', 'maintain_state': True, 'state_directory': 'out\\state', 'instruments': {'simulate_instruments': False}, 'use_profiles': False, 'profiles': {}}
2022-06-28 13:40:07.861 | INFO     | autodidaqt.core:start:775 - Configuring Qt application and styles
2022-06-28 13:40:07.879 | INFO     | autodidaqt.core:configure_event_loop:746 - Configuring async runtime
2022-06-28 13:40:07.879 | INFO     | autodidaqt.core:configure_event_loop:753 - Using asyncio for async support.
2022-06-28 13:40:07.879 | INFO     | autodidaqt.core:configure_event_loop:763 - Setting custom exception handler on async loop
2022-06-28 13:40:08.085 | INFO     | autodidaqt.core:launch_panel:130 - Opening panel _instrument_manager
2022-06-28 13:40:08.086 | INFO     | autodidaqt.panels.instrument_manager:launch_panel:21 - Instrument Manager: Opening panel power_meter
2022-06-28 13:40:08.119 | INFO     | autodidaqt.core:master:548 - Started async loop.
2022-06-28 13:40:08.122 | INFO     | autodidaqt.core:master:567 - Running actor .prepare
2022-06-28 13:40:08.122 | ERROR    | autodidaqt.core:handle_exception:382 - Caught Unhandled: Could not locate a VISA implementation. Install either the IVI binary or pyvisa-py.
2022-06-28 13:40:08.122 | WARNING  | autodidaqt.core:shutdown:417 - Shutting down due to exception.
2022-06-28 13:40:08.122 | INFO     | autodidaqt.core:shutdown:419 - Shutting down process pool.
2022-06-28 13:40:08.122 | INFO     | autodidaqt.core:shutdown:421 - Finished shutting down process pool.
2022-06-28 13:40:08.122 | INFO     | autodidaqt.core:shutdown:423 - Saving...
2022-06-28 13:40:08.122 | INFO     | autodidaqt.core:save_state:722 - Saving application state.
2022-06-28 13:40:08.122 | INFO     | autodidaqt.core:save_state:730 - Finished saving application state.
2022-06-28 13:40:08.132 | INFO     | autodidaqt.core:shutdown:431 - Sending graceful shutdown requests.
2022-06-28 13:40:08.132 | ERROR    | autodidaqt.core:handle_exception:382 - Caught Unhandled: 'NoneType' object has no attribute 'put'
2022-06-28 13:40:19.536 | INFO     | autodidaqt.core:start:794 - Closed autodidaqt successfully.
